### ISSUE TITLE
BS4 - Alerts not showing

### ISSUE THREAD

**Issue by Moc** [e107inc/e107#3686]
In a bootstrap 4 theme, alerts (info, warning, error messages) are not visible on frontend because there is a CSS conflict with transitions.css from Bootstrap 4. 

```css
.fade:not(.show) {
    opacity: 0;
}
```

If I add the following to theme.php, it is fixed:

```css
.s-message.fade {
opacity: 1 !important;
visibility: inherit;
}
``` 
I (Jimmi! 😄 ) took this code from the vstore plugin.

I am not sure if this is the right fix, so I created an issue for it. Perhaps there's a cleaner way to do it as this is more a bandaid.
